(function() {var implementors = {};
implementors["fork_tree"] = [{"text":"impl&lt;E:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/1.55.0/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/1.55.0/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"fork_tree/enum.Error.html\" title=\"enum fork_tree::Error\">Error</a>&lt;E&gt;","synthetic":false,"types":["fork_tree::Error"]}];
implementors["sc_allocator"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.55.0/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"sc_allocator/enum.Error.html\" title=\"enum sc_allocator::Error\">Error</a>","synthetic":false,"types":["sc_allocator::error::Error"]}];
implementors["sc_executor_common"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.55.0/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"sc_executor_common/error/enum.Error.html\" title=\"enum sc_executor_common::error::Error\">Error</a>","synthetic":false,"types":["sc_executor_common::error::Error"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.55.0/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"sc_executor_common/error/enum.WasmError.html\" title=\"enum sc_executor_common::error::WasmError\">WasmError</a>","synthetic":false,"types":["sc_executor_common::error::WasmError"]}];
implementors["sc_keystore"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.55.0/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"sc_keystore/enum.Error.html\" title=\"enum sc_keystore::Error\">Error</a>","synthetic":false,"types":["sc_keystore::Error"]}];
implementors["sc_telemetry"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.55.0/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"sc_telemetry/enum.Error.html\" title=\"enum sc_telemetry::Error\">Error</a>","synthetic":false,"types":["sc_telemetry::error::Error"]}];
implementors["sp_core"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.55.0/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"sp_core/ed25519/enum.PublicError.html\" title=\"enum sp_core::ed25519::PublicError\">PublicError</a>","synthetic":false,"types":["sp_core::ed25519::PublicError"]}];
implementors["sp_database"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.55.0/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"sp_database/error/struct.DatabaseError.html\" title=\"struct sp_database::error::DatabaseError\">DatabaseError</a>","synthetic":false,"types":["sp_database::error::DatabaseError"]}];
implementors["sp_maybe_compressed_blob"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.55.0/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"sp_maybe_compressed_blob/enum.Error.html\" title=\"enum sp_maybe_compressed_blob::Error\">Error</a>","synthetic":false,"types":["sp_maybe_compressed_blob::Error"]}];
implementors["sp_state_machine"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.55.0/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"sp_state_machine/enum.ExecutionError.html\" title=\"enum sp_state_machine::ExecutionError\">ExecutionError</a>","synthetic":false,"types":["sp_state_machine::error::ExecutionError"]}];
implementors["sp_trie"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.55.0/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"sp_trie/enum.Error.html\" title=\"enum sp_trie::Error\">Error</a>","synthetic":false,"types":["sp_trie::error::Error"]},{"text":"impl&lt;L:&nbsp;<a class=\"trait\" href=\"sp_trie/trait.TrieConfiguration.html\" title=\"trait sp_trie::TrieConfiguration\">TrieConfiguration</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/1.55.0/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"sp_trie/enum.CompactProofError.html\" title=\"enum sp_trie::CompactProofError\">Error</a>&lt;L&gt;","synthetic":false,"types":["sp_trie::trie_codec::Error"]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()